[package]
name = "emissions_app_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "emissions_app"


[dependencies]
yew = { version = "0.20", features = ["csr"] }
gloo-net = "0.2"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen-futures = "0.4"
graphql_client = "0.12.0"
serde_json = "1"
web-sys = "0.3"
yew-hooks = "0.2"
yew-router = "0.17.0"
common = { path = "../common", features = ["client"] }
uuid = { version = "1", features = ["serde"] }
chrono = { version = "0.4", features = ["wasmbind", "serde"] }
