version: '3'
services:
  api:
    image: nomanleftbehind/methane-emissions-management
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api.methane-emissions-management
    depends_on:
      - db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports: 
      - "8081:8081"

  db:
    image: "postgres:15.2-alpine"
    restart: always
    container_name: db.methane-emissions-management
    ports:
      - "5435:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  db:
    driver: local