version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api.todo
    depends_on:
      - db
    # environment:
    #   - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/emissions
    ports: 
      - "8081:8081"

  db:
    image: "postgres:15.2-alpine"
    restart: always
    container_name: db.todo
    ports:
      - "5435:5432"
    volumes:
      - db:/var/lib/postgresql/data
      # - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}

volumes:
  db:
    driver: local