[package]
edition = "2021"
name = "emissions_app_derive"
version = "1.0.0"
authors = ["Doma Sucic <domagoj.sucic1@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1"