mutation Login($loginUserInput: LoginUserInput!) {
	login(loginUserInput: $loginUserInput) {
		id
		email
		role
	}
}

mutation Logout {
	logout
}

mutation Register($registerUserInput: RegisterUserInput!) {
  register(registerUserInput: $registerUserInput) {
    id
		email
		role
  }
}