query AllFacilities($limitOffsetInput: LimitOffsetInput) {
	allFacilities(limitOffsetInput: $limitOffsetInput) {
		id
		idpa
		name
		type
		createdAt
		updatedAt
	}
}

query Facilities($by: FacilityBy!) {
	facilitiesBy(by: $by) {
		id
		idpa
		name
		type
		createdAt
		updatedAt
	}
}

query Controllers($by: ControllersBy!) {
	controllersBy(by: $by) {
		id
		manufacturer {
			manufacturer
		}
		application {
			application
		}
		model
		serialNumber
	}
}

query Me {
	me {
		email
		id
	}
}

query ControllersBy($by: ControllersBy!) {
	controllersBy(by: $by) {
		id
		fdcRecId
		model
		serialNumber
		application {
			application
		}
		manufacturer {
			manufacturer
		}
	}
}
