application:
  host: 0.0.0.0
  base_url: "http://0.0.0.0"
database:
  require_ssl: false # set to true when deploying the app. This was set to false to get it to run in Docker container locally.
email_client:
  base_url: "https://api.postmarkapp.com"
