use serde::Serialize;

#[cfg_attr(not(target_arch = "wasm32"), derive(async_graphql::Enum))]
#[derive(Copy, Clone, Eq, PartialEq, Debug, Serialize)]
pub enum UpdateFieldVariant {
    // Facility
    FacilityIdpa,
    FacilityName,
    FacilityType,
    // Site
    SiteFacilityId,
    SiteFdcRecId,
    SiteName,
    SiteType,
    SiteDescription,
    // Device Manufacturer
    DeviceManufacturerManufacturer,
    // Survey Equipment
    SurveyEquipmentMake,
    SurveyEquipmentModel,
    // Gas Analysis
    GasAnalysisDate,
    GasAnalysisH2,
    GasAnalysisHe,
    GasAnalysisN2,
    GasAnalysisCo2,
    GasAnalysisH2s,
    GasAnalysisC1,
    GasAnalysisC2,
    GasAnalysisC3,
    GasAnalysisC4I,
    GasAnalysisC4N,
    GasAnalysisC5I,
    GasAnalysisC5N,
    GasAnalysisC6,
    GasAnalysisC7Plus,
    // Pneumatic Instrument
    PneumaticInstrumentSiteId,
    PneumaticInstrumentType,
    PneumaticInstrumentManufacturerId,
    PneumaticInstrumentModel,
    PneumaticInstrumentSerialNumber,
    PneumaticInstrumentStartDate,
    PneumaticInstrumentEndDate,
    // Pneumatic Instrument Emission Rate
    PneumaticInstrumentEmissionRatePneumaticInstrumentId,
    PneumaticInstrumentEmissionRateDate,
    PneumaticInstrumentEmissionRateRate,
    // Pneumatic Instrument Controlled Characterization
    PneumaticInstrumentControlledCharacterizationPneumaticInstrumentId,
    PneumaticInstrumentControlledCharacterizationStartDate,
    PneumaticInstrumentControlledCharacterizationEndDate,
    PneumaticInstrumentControlledCharacterizationControlDevice,
    PneumaticInstrumentControlledCharacterizationComment,
    // Pneumatic Instrument Control Device Inactivity
    PneumaticInstrumentControlDeviceInactivityPneumaticInstrumentControlledCharacterizationId,
    PneumaticInstrumentControlDeviceInactivityStartDate,
    PneumaticInstrumentControlDeviceInactivityEndDate,
    PneumaticInstrumentControlDeviceInactivityReason,
    PneumaticInstrumentControlDeviceInactivityComment,
    // Pneumatic Instrument Month Hours
    PneumaticInstrumentMonthHoursPneumaticInstrumentId,
    PneumaticInstrumentMonthHoursMonth,
    PneumaticInstrumentMonthHoursHoursOn,
    // Pneumatic Instrument Month Methane Emission Override
    PneumaticInstrumentMonthMethaneEmissionOverridePneumaticInstrumentId,
    PneumaticInstrumentMonthMethaneEmissionOverrideMonth,
    PneumaticInstrumentMonthMethaneEmissionOverrideGasVolume,
    PneumaticInstrumentMonthMethaneEmissionOverrideComment,
    // Level Controller
    LevelControllerSiteId,
    LevelControllerManufacturerId,
    LevelControllerModel,
    LevelControllerSerialNumber,
    LevelControllerStartDate,
    LevelControllerEndDate,
    // Level Controller Actuation Frequency
    LevelControllerActuationFrequencyLevelControllerId,
    LevelControllerActuationFrequencyDate,
    LevelControllerActuationFrequencyActuationFrequency,
    // Level Controller Emission Rate
    LevelControllerEmissionRateLevelControllerId,
    LevelControllerEmissionRateDate,
    LevelControllerEmissionRateRate,
    // Level Controller Controlled Characterization
    LevelControllerControlledCharacterizationLevelControllerId,
    LevelControllerControlledCharacterizationStartDate,
    LevelControllerControlledCharacterizationEndDate,
    LevelControllerControlledCharacterizationControlDevice,
    LevelControllerControlledCharacterizationComment,
    // Level Controller Control Device Inactivity
    LevelControllerControlDeviceInactivityLevelControllerControlledCharacterizationId,
    LevelControllerControlDeviceInactivityStartDate,
    LevelControllerControlDeviceInactivityEndDate,
    LevelControllerControlDeviceInactivityReason,
    LevelControllerControlDeviceInactivityComment,
    // Level Controller Month Hours
    LevelControllerMonthHoursLevelControllerId,
    LevelControllerMonthHoursMonth,
    LevelControllerMonthHoursHoursOn,
    // Level Controller Month Methane Emission Override
    LevelControllerMonthMethaneEmissionOverrideLevelControllerId,
    LevelControllerMonthMethaneEmissionOverrideMonth,
    LevelControllerMonthMethaneEmissionOverrideGasVolume,
    LevelControllerMonthMethaneEmissionOverrideComment,
    // Pneumatic Pump
    PneumaticPumpSiteId,
    PneumaticPumpManufacturerId,
    PneumaticPumpModel,
    PneumaticPumpSerialNumber,
    PneumaticPumpStartDate,
    PneumaticPumpEndDate,
    // Pneumatic Pump Emission Rate
    PneumaticPumpEmissionRatePneumaticPumpId,
    PneumaticPumpEmissionRateDate,
    PneumaticPumpEmissionRateRate,
    // Pneumatic Pump Controlled Characterization
    PneumaticPumpControlledCharacterizationPneumaticPumpId,
    PneumaticPumpControlledCharacterizationStartDate,
    PneumaticPumpControlledCharacterizationEndDate,
    PneumaticPumpControlledCharacterizationControlDevice,
    PneumaticPumpControlledCharacterizationComment,
    // Pneumatic Pump Control Device Inactivity
    PneumaticPumpControlDeviceInactivityPneumaticPumpControlledCharacterizationId,
    PneumaticPumpControlDeviceInactivityStartDate,
    PneumaticPumpControlDeviceInactivityEndDate,
    PneumaticPumpControlDeviceInactivityReason,
    PneumaticPumpControlDeviceInactivityComment,
    // Pneumatic Pump Month Hours
    PneumaticPumpMonthHoursPneumaticPumpId,
    PneumaticPumpMonthHoursMonth,
    PneumaticPumpMonthHoursHoursOn,
    // Pneumatic Pump Month Methane Emission Override
    PneumaticPumpMonthMethaneEmissionOverridePneumaticPumpId,
    PneumaticPumpMonthMethaneEmissionOverrideMonth,
    PneumaticPumpMonthMethaneEmissionOverrideGasVolume,
    PneumaticPumpMonthMethaneEmissionOverrideComment,
    // Compressor
    CompressorSiteId,
    CompressorFdcRecId,
    CompressorType,
    CompressorName,
    CompressorSerialNumber,
    CompressorPower,
    CompressorThrowCount,
    CompressorInstallDate,
    CompressorRemoveDate,
    // Compressor Seal
    CompressorSealType,
    CompressorSealDescription,
    // Compressor Seal Test
    CompressorSealTestCompressorSealId,
    CompressorSealTestStartDate,
    CompressorSealTestEndDate,
    CompressorSealTestRate,
    CompressorSealTestTestingPoint,
    CompressorSealTestSurveyEquipmentId,
    // Compressor Emission Survey
    CompressorEmissionSurveyCompressorId,
    CompressorEmissionSurveyStartDate,
    CompressorEmissionSurveyEndDate,
    CompressorEmissionSurveyRate,
    CompressorEmissionSurveySurveyPoint,
    CompressorEmissionSurveyLeakDuration,
    CompressorEmissionSurveySurveyEquipmentId,
    // Compressor Controlled Characterization,
    CompressorControlledCharacterizationCompressorId,
    CompressorControlledCharacterizationStartDate,
    CompressorControlledCharacterizationEndDate,
    CompressorControlledCharacterizationControlDevice,
    CompressorControlledCharacterizationComment,
    // Compressor Control Device Inactivity
    CompressorControlDeviceInactivityCompressorControlledCharacterizationId,
    CompressorControlDeviceInactivityStartDate,
    CompressorControlDeviceInactivityEndDate,
    CompressorControlDeviceInactivityReason,
    CompressorControlDeviceInactivityComment,
    // Compressor Month Hours
    CompressorMonthHoursCompressorId,
    CompressorMonthHoursMonth,
    CompressorMonthHoursPressurizedHours,
    // Compressor Seal Month Methane Emission Override
    CompressorSealMonthMethaneEmissionOverrideCompressorSealId,
    CompressorSealMonthMethaneEmissionOverrideMonth,
    CompressorSealMonthMethaneEmissionOverrideGasVolume,
    CompressorSealMonthMethaneEmissionOverrideComment,
    // Compressor Blowdown Override
    CompressorBlowdownOverrideCompressorId,
    CompressorBlowdownOverrideDate,
    CompressorBlowdownOverrideGasVolume,
    CompressorBlowdownOverrideComment,
    // Storage Tank
    StorageTankSiteId,
    StorageTankStartDate,
    StorageTankEndDate,
    // Storage Tank Change
    StorageTankChangeStorageTankId,
    StorageTankChangeDate,
    StorageTankChangeIA,
    StorageTankChangeApiDensity,
    StorageTankChangeTemperature,
    StorageTankChangePressure,
    StorageTankChangeCalculationMethod,
    //Storage Tank Emission Survey
    StorageTankEmissionSurveyStorageTankId,
    StorageTankEmissionSurveyStartDate,
    StorageTankEmissionSurveyEndDate,
    StorageTankEmissionSurveyRate,
    StorageTankEmissionSurveySurveyPoint,
    StorageTankEmissionSurveyLeakDuration,
    StorageTankEmissionSurveySurveyEquipmentId,
    // Storage Tank Controlled Characterization,
    StorageTankControlledCharacterizationStorageTankId,
    StorageTankControlledCharacterizationStartDate,
    StorageTankControlledCharacterizationEndDate,
    StorageTankControlledCharacterizationControlDevice,
    StorageTankControlledCharacterizationComment,
    // Storage Tank Control Device Inactivity
    StorageTankControlDeviceInactivityStorageTankControlledCharacterizationId,
    StorageTankControlDeviceInactivityStartDate,
    StorageTankControlDeviceInactivityEndDate,
    StorageTankControlDeviceInactivityReason,
    StorageTankControlDeviceInactivityComment,
    // Storage Tank Month Liquid Hydrocarbon Entering
    StorageTankMonthLiquidHydrocarbonEnteringStorageTankId,
    StorageTankMonthLiquidHydrocarbonEnteringMonth,
    StorageTankMonthLiquidHydrocarbonEnteringLiquidHydrocarbonVolume,
    // Storage Tank Month Methane Emission Override
    StorageTankMonthMethaneEmissionOverrideStorageTankId,
    StorageTankMonthMethaneEmissionOverrideMonth,
    StorageTankMonthMethaneEmissionOverrideGasVolume,
    StorageTankMonthMethaneEmissionOverrideComment,
}

#[cfg_attr(not(target_arch = "wasm32"), derive(async_graphql::Enum))]
#[derive(Copy, Clone, Eq, PartialEq, Debug, Serialize)]
pub enum DeleteEntryVariant {
    Facility,
    Site,
    DeviceManufacturer,
    SurveyEquipment,
    GasAnalysis,
    // Pneumatic Instrument
    PneumaticInstrument,
    PneumaticInstrumentEmissionRate,
    PneumaticInstrumentControlledCharacterization,
    PneumaticInstrumentControlDeviceInactivity,
    PneumaticInstrumentMonthHours,
    PneumaticInstrumentMonthMethaneEmissionOverride,
    // Level Controller
    LevelController,
    LevelControllerActuationFrequency,
    LevelControllerEmissionRate,
    LevelControllerControlledCharacterization,
    LevelControllerControlDeviceInactivity,
    LevelControllerMonthHours,
    LevelControllerMonthMethaneEmissionOverride,
    // Pneumatic Pump
    PneumaticPump,
    PneumaticPumpEmissionRate,
    PneumaticPumpControlledCharacterization,
    PneumaticPumpControlDeviceInactivity,
    PneumaticPumpMonthHours,
    PneumaticPumpMonthMethaneEmissionOverride,
    // Compressor Seal
    Compressor,
    CompressorSeal,
    CompressorSealTest,
    CompressorEmissionSurvey,
    CompressorControlledCharacterization,
    CompressorControlDeviceInactivity,
    CompressorMonthHours,
    CompressorSealMonthMethaneEmissionOverride,
    CompressorBlowdown,
    CompressorBlowdownOverride,
    // Storage Tank
    StorageTank,
    StorageTankChange,
    StorageTankEmissionSurvey,
    StorageTankControlledCharacterization,
    StorageTankControlDeviceInactivity,
    StorageTankGasInSolutionFactorCalculated,
    StorageTankMonthLiquidHydrocarbonEntering,
    StorageTankMonthMethaneEmissionOverride,
}
